### ISSUE TITLE
What's the purpose of "--nsfw" you will still get NSFW results w/o using it?

### ISSUE THREAD

**Issue by abraxas86** [Haidra-Org/AI-Horde-CLI#10]
I'm sure this is a stupid question, but what's the point on using `--nsfw` if running spicy prompts without it will still return NSFW images?

Ideally, I wish we could tweak the `--censor_nsfw` since it seems to censor things that likely aren't actually NSFW

**Comment by db0** [comment]
using nsfw means only nsfw workers will pick up your job. If you don't use it, a SFW worker might pick it up and run a censor filter over it
